# -*- rd -*-

= README.en

$Id: README.en 667 2006-08-20 02:59:15Z kou $

== Name

scim

== Author

Kouhei Sutou <kou@cozmixng.org>

== Licence

Ruby's

== Mailing list

Send mail that To field is cozdev@cozmixng.quickml.com , Cc
field is kou@cozmixng.org and Subject and Body contain
somthig to
((<"cozdev@cozmixng.quickml.com"|URL:mailto:cozdev@cozmixng.quickml.com?cc=kou@cozmixng.org&subject=Join!>)).

Note that this mailing list's main language is Japanese. But
English mail is welcome too.

== What's this?

This is a binding of
((<SCIM|URL:http://www.scim-im.org/>)). An interface between
Ruby and C is generated by
((<SWIG|URL:http://www.swig.org/>)).

== Dependency

  * ((<SCIM|URL:http://www.scim-im.org/>))
  * ((<SWIG|URL:http://www.swig.org/>))

== Download

((<URL:http://www.cozmixng.org/~kou/download/scim.tar.gz>))

  % svn co http://www.cozmixng.org/repos/ruby/scim/trunk scim

== Install

  % ruby setup.rb config

If you want to add include path, type like the following.

  % ruby setup.rb config -- --with-opt-include=path1:path2:...

If you want to add library path, type like the following.

  % ruby setup.rb config -- --with-opt-lib=path1:path2:...

You can specify both of --with-opt-include and
--with-opt-lib options.

And rest is same as alway.

  % ruby setup.rb setup
  # ruby setup.rb install

== Usage

See
((<SCIM-RubyBridge|URL:http://www.cozmixng.org/~rwiki/?cmd=view;name=SCIM-RubyBridge>)). Sorry.

== Thanks
